export const duongdan = {
  home: "/",
  dashboard: "/dashboard",
  accounts: "accounts",
  detail: "/detail",
  login: "/login",
  profile: "/profile",
  notfound: "/notfound",
  register: "/register",
  cart: "/cart",
  checkout: "/checkout",
  tracking: "/tracking",
  orderHistory: "/order-history",
  orderSuccess: "/order-success",
};
